use_frameworks!

platform :ios, '12.0'

target 'modepend_Example' do
  
  pod 'modepend/Kingfisher', :path => '../'
  
#  pod 'modepend/SDWebImage', :path => '../'

  pod 'soapp', :path => '~/hitching_ios/Hitching/soapp'
  pod 'soapp/AppPlugins', :path => '~/hitching_ios/Hitching/soapp'

end
